version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    #command: bundle exec bash
    #rails s -p 3000 -b '0.0.0.0'
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    #tty: true
    volumes:
      - .:/myapp
      #share bundler cache so we can update it without rebuilding the image
      #- ./bundle_cache:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
